In [ ]:
import tensorflow as tf
import numpy as np
from scipy.special import expit
import random

In [ ]:
tf.__version__
random.randint(0, 5)

0

In [ ]:
pesos = [[]]
qntNeuronios, qntCamadas, qntNeuroniosCamadaSaida = (2, 3, 1)
#define as entradas e transforma em matriz
entradas = np.array([1, 2, 3]).reshape(-1, 1)
#adiciona a camada de entrada
pesos[0] = np.random.rand(qntNeuronios, len(entradas))


In [ ]:
#adiciona os pesos da camada oculta
for i in range(qntCamadas-1):
  pesos.append(np.random.rand(qntNeuronios, qntNeuronios))

In [ ]:
pesos

[array([[0.23923299, 0.34401709, 0.98664399],
        [0.40891383, 0.41900176, 0.50671528]]),
 array([[0.11290991, 0.62574922],
        [0.5829799 , 0.18208165]]),
 array([[0.02078588, 0.34781001],
        [0.3527184 , 0.82655592]]),
 array([[0.39166063, 0.92459288]])]

In [ ]:
pesos.append(np.random.rand(qntNeuroniosCamadaSaida, qntNeuronios))

In [ ]:
pesos

[array([[0.23923299, 0.34401709, 0.98664399],
        [0.40891383, 0.41900176, 0.50671528]]),
 array([[0.11290991, 0.62574922],
        [0.5829799 , 0.18208165]]),
 array([[0.02078588, 0.34781001],
        [0.3527184 , 0.82655592]]),
 array([[0.39166063, 0.92459288]]),
 array([[0.6146098 , 0.73136585]])]

In [ ]:
qntNeuroniosCamadaSaida

1

In [ ]:
def feedForward():
  listaSaidasEntradas = []
  aux = entradas
  listaSaidasEntradas.append(aux)
  for i in range(len(pesos)):
    aux = np.dot(pesos[i], aux)
    aux = expit(aux)
    listaSaidasEntradas.append(aux)
  return aux, listaSaidasEntradas

In [ ]:
resultado, listaSaidasEntradas = feedForward()

In [ ]:
listaSaidasEntradas

[array([[1],
        [2],
        [3]]), array([[0.99308957],
        [0.98618669]]), array([[0.86543415],
        [0.78961478]]), array([[0.76580823],
        [0.78140581]]), array([[0.7661503]])]

In [ ]:
resultado

array([[0.7661503]])

In [ ]:
class redeNeural:
  def __init__(self, qntNeuronios,qntCamadas,qntNeuroniosCamadaSaida, entradas, resultadoEsperado):
    self.qntNeuronios, self.qntCamadas, self.qntNeuroniosCamadaSaida, self.resultadoEsperado = (qntNeuronios, qntCamadas, qntNeuroniosCamadaSaida, resultadoEsperado)
    self.entradas = np.array(entradas)
    self.pesos = [[]]
    self.pesos[0] = np.random.randn(qntNeuronios, len(entradas[0]))
    for i in range(self.qntCamadas-1):
      self.pesos.append(np.random.randn(self.qntNeuronios, self.qntNeuronios))
    self.pesos.append(np.random.randn(qntNeuroniosCamadaSaida, qntNeuronios))

  def feedForward(self, entrada):
    self.listaSaidasEntradas = []
    self.listaSaidasEntradas.clear()
    aux = np.array(entrada)
    self.listaSaidasEntradas.append(aux)
    for i in range(len(self.pesos)):
      aux = np.dot(self.pesos[i], aux)
      aux = step(aux)
      self.listaSaidasEntradas.append(aux)
    return aux

  def reajustePesos(self, alpha, epocas):
    for epoca in range(epocas):
      #percorre as entradas
      for treino in range(len(self.entradas)):
        #treino = random.randint(0, len(self.entradas)-1)
        resultadoObtido = self.feedForward(self.entradas[treino])
        erro = self.resultadoEsperado[treino] - resultadoObtido[0]
        print(erro)
        #print(f'lista completa {self.listaSaidasEntradas}')
        
        #percorre a camada
        for i in range(len(self.pesos)-1, -1, -1):
          #percorre linha
          for j in range(len(self.pesos[i])):
            #percorre coluna
            for h in range(len(self.pesos[i][j])):
              #print(rede.listaSaidasEntradas[i][h])
              #print(f'peso = {rede.pesos[i][j][h]} entrada = {rede.listaSaidasEntradas[i][h][0]}')
              #print(f'pesos {self.pesos[i][j][h]}')
              #print(f'lista = {self.listaSaidasEntradas[i][h]}')
              self.pesos[i][j][h] = self.pesos[i][j][h] + (alpha * self.listaSaidasEntradas[i][h] * erro)
              #print(f'pesos corrigido {self.pesos[i][j][h]}')

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def step(self, x):
    for i in range(len(x)):
      if x[i] <= 0:
        x[i] = 0
      else:
        x[i] = 1
    return x  
    

In [ ]:
treinamentos = [[1,0,1],[0,0,1],[0,1,1], [1,1,1]]
resultados = [1,0,1,0]

rede = redeNeural(4, 4, 1, treinamentos, resultados)

In [ ]:
rede.pesos

[array([[-0.00236559,  1.60289624, -0.81827251],
        [ 0.65844092, -0.1525047 ,  0.93137141],
        [-0.95276477, -0.846857  , -0.60752196],
        [ 0.87546679,  0.80024292, -0.2854539 ]]),
 array([[-1.01942777, -2.42007569, -0.80268868,  0.08150477],
        [-0.3425873 , -0.37245766, -1.04883272,  0.44749702],
        [-0.33926319,  1.62079049,  0.30712848, -0.93447555],
        [ 0.43877883,  0.65298396, -0.12369282, -0.57422081]]),
 array([[-2.51900076,  0.30943969,  0.05169677, -0.22065257],
        [ 0.28831618,  0.14811532,  0.86481141, -0.24979724],
        [ 1.04746943,  0.00350371, -0.30595747, -1.67365395],
        [ 0.56571622,  1.05925906,  0.81000954,  0.487278  ]]),
 array([[-0.10379768,  0.53168133,  0.23007815,  0.14784213],
        [ 1.7192227 , -2.19485641, -0.49472623, -0.21556404],
        [ 1.03007111, -0.11159078, -0.63096758, -0.69798618],
        [ 0.79748734,  1.87208059, -0.45785127,  0.30083672]]),
 array([[ 2.75216088, -1.36370052,  1.04362138,  0.3

In [ ]:
rede.feedForward([1,0,1])

array([0.])